# yaml-language-server: $schema=../schema/preprocess.schema.json
dataset_name: "mito_live"
pipeline: "recon_timelapse_simple"
data_type: "recon"
fmt: "timelapse"

registry:
  description: null
  
pipeline_cfg:
  base_subfolder: ""
  input_subfolder: ""
  combine_subfolders: True
  crop_size: null
  remove_first: True
  
log:
  enabled: true

split:
  enabled: true
  mode: "random"
  random:
    seed: 0
    val_fraction: 0.2
    test_fraction: 0.2
  manual:
    match_by: "sample_id"
    val: []
    test: []
  reuse: null
